[project]
name = "antdemo-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.8.1",
    "six>=1.16.0",
    "websockets>=13.1,<15.0",
]
